# Generated by Django 3.1.13 on 2025-12-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20210325_1619'),
        ('competitions', '0003_auto_20240903_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='pair_finalists',
        ),
        migrations.AddField(
            model_name='competition',
            name='self_judging_final',
            field=models.BooleanField(blank=True, default=False, verbose_name='Self Judging Final'),
        ),
        migrations.CreateModel(
            name='SelfJudgeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('result', models.IntegerField(verbose_name='Place')),
                ('comp_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.registration')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'unique_together': {('competitor', 'comp_reg')},
            },
        ),
    ]
