# Generated by Django 2.2.12 on 2020-05-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_merge_20191028_1924'),
        ('faq', '0005_remove_untranslated_fields'),
    ]

    operations = [
    ]
