# Generated by Django 2.2.13 on 2020-06-12 13:37

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_merge_20200516_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='faq.FAQ'),
        ),
    ]
