# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181109_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMemberTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('firstName', models.CharField(blank=True, max_length=50, null=True, verbose_name='First name')),
                ('lastName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('bio', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text="Insert the instructor's bio here.  Use HTML to include videos, formatting, etc.", null=True, verbose_name='Bio text')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.StaffMember')),
            ],
            options={
                'managed': True,
                'db_tablespace': '',
                'default_permissions': (),
                'db_table': 'core_staffmember_translation',
                'verbose_name': 'Staff member Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='staffmembertranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
