# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fix_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstaffmember',
            options={'ordering': ('event', 'staffMember__id'), 'verbose_name': 'Event staff member', 'verbose_name_plural': 'Event staff members'},
        ),
    ]
