# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190124_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='order',
            field=models.FloatField(default=10, help_text='This is used to apply manual order for Instructors list.', verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='staffmemberlistpluginmodel',
            name='orderChoice',
            field=models.CharField(choices=[('firstName', 'First Name'), ('lastName', 'Last Name'), ('status', 'Instructor Status'), ('manual', 'Manual Order'), ('random', 'Randomly Ordered')], max_length=10, verbose_name='Order By'),
        ),
    ]
