# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190210_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Customer ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sheet_id',
            field=models.CharField(default='', max_length=50, verbose_name='Sheet ID'),
        ),
    ]
