# Generated by Django 2.2.12 on 2020-05-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200124_1349'),
        ('core', '0032_auto_20190411_1323'),
    ]

    operations = [
    ]
