# Generated by Django 3.1.7 on 2021-03-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210324_0009'),
        ('core', '0035_auto_20200612_1710'),
    ]

    operations = [
    ]
